import Head from "next/head";
import React from "react";

import styles from  "./Layout.module.css";

class Layout extends React.Component {
  render() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className={styles.main}>
          {this.props.children}
        </div>
        <footer>
            <div>
                <p className={styles.footerContentPara}>advance react tutorial</p>
            </div>
        </footer>
      </>
    );
  }
}

export default Layout;
